### Create table

In [ ]:
import psycopg2 as sql
import pandas as pd 
import csv 

connection = sql.connect(host = 'localhost',
                  dbname = 'suppliers',
                  user = 'postgres',
                  password = 'Bakitzhan566*566',
                  port = '5432' 
)

cursor = connection.cursor()

cursor.execute("""
CREATE TABLE phonebook2 (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    surname VARCHAR(255) NOT NULL,
    phone VARCHAR(255) NOT NULL
);
""") 

print("Hurray! Table is created")

connection.commit()

cursor.close()

connection.close

### Pattern

In [ ]:
import psycopg2 as sql
import pandas as pd
import csv

connection = sql.connect(host='localhost',
                         dbname='suppliers',
                         user='postgres',
                         password='Bakitzhan566*566',
                         port='5432')

cursor = connection.cursor()

insert_data = """
    INSERT INTO phonebook2 (name, surname, phone)
    VALUES (%s, %s, %s);"""
all_table = '''
    SELECT id, name, surname, phone FROM phonebook2'''
base_query = '''
    SELECT * FROM phonebook2
    WHERE '''

def File():
    with open("data.csv", "r") as file:
        data = csv.reader(file, delimiter=',')
        for row in data:
            name, surname, phone = row
            cursor.execute(insert_data, (name, surname, phone))

method = input("Do you want to work with data Y/n?")

if method == "Y":
    File()
    method3 = input('By what kind of pattern do you whant to query [name/surname/phone]?')

    if method3 == 'name':
        base_query += '''name '''
        string = input("Enter string")
        method4 = int(input('''
        1-name is equal to ...
        2-name starts with the ...
        3-name ends with the ...
        4-name contains the ...
        '''))
        if method4 == 1: base_query += f"='{string}'"
        elif method4 == 2: base_query += f" iLIKE '{string}%'"
        elif method4 == 3: base_query += f" iLIKE '%{string}'"
        elif method4 == 4: base_query += f" iLIKE '%{string}%'"
        else: print("Something went wrong")

    elif method3 == 'surname':
        base_query += '''surname '''
        string = input("Enter string")
        method4 = int(input('''
        1-surname is equal to ...
        2-surname starts with the ...
        3-surname ends with the ...
        4-surname contains the ...
        '''))
        if method4 == 1: base_query += f"='{string}'"
        elif method4 == 2: base_query += f" iLIKE '{string}%'"
        elif method4 == 3: base_query += f" iLIKE '%{string}'"
        elif method4 == 4: base_query += f" iLIKE '%{string}%'"
        else: print("Something went wrong")

    elif method3 == 'phone':
        base_query += '''phone '''
        integ = input("Enter the pattern phone")
        method4 = int(input('''
        1-phone is equal to ...
        2-phone starts with the ...
        3-phone ends with the ...
        4-phone contains the ...
        '''))
        if method4 == 1: base_query += f"='{integ}'"
        elif method4 == 2: base_query += f" iLIKE '{integ}%'"
        elif method4 == 3: base_query += f" iLIKE '%{integ}'"
        elif method4 == 4: base_query += f" iLIKE '%{integ}%'"
        else: print("Something went wrong")

    cursor.execute(base_query)
    data = [row for row in cursor.fetchall()]
    dataframe = pd.DataFrame(data, columns=['id', 'Name', 'Surname', 'Phone'])

else:
    print("Ok . Goodluck!")

connection.commit()

cursor.close()

connection.close()
dataframe

### INSERT OR UPDATE

In [ ]:
import psycopg2 as sql
import pandas as pd

connection = sql.connect(
    host='localhost',

    dbname='suppliers',
    user='postgres',
    password='Bakitzhan566*566',
    port='5432'
)

cursor = connection.cursor()

insert_data = """
    INSERT INTO phonebook2 (name, surname, phone)
    VALUES (%s, %s, %s);
"""

update_data = '''
    UPDATE phonebook2 SET {} = %s WHERE id = %s;
'''

method1 = input("Do you want to insert data or update? ")

if method1 == "insert":
    name = input("Please enter the name: ")
    surname = input("Please enter the surname: ")
    phone = input("Please enter the phone: ")
    cursor.execute(insert_data, (name, surname, phone))
elif method1 == "update":
    id = input('Enter the id: ')
    column = input('Enter the column: ')
    update_query = update_data.format(column)
    change_data = input('Enter the new element: ')
    cursor.execute(update_query, (change_data, id))
else:
    print('Invalid input')

all_table = '''
    SELECT * FROM phonebook2 
    ORDER BY id ASC
'''
cursor.execute(all_table)
data = [row for row in cursor.fetchall()]
dataframe = pd.DataFrame(data, columns=['id', 'name', 'surname', 'phone'])
dataframe = dataframe.set_index('id')
connection.commit()

cursor.close()

connection.close()
dataframe.head(25)

### INSERT MANY USERS

In [ ]:
import psycopg2 as sql
import pandas as pd

connection = sql.connect(
    host='localhost',

    dbname='suppliers',
    user='postgres',
    password='Bakitzhan566*566',
    port='5432'
)

cursor = connection.cursor()

insert_data = """
    INSERT INTO phonebook2 (name, surname, phone)
    VALUES (%s, %s, %s);
"""

names = []
surnames = []
phones = []
temp = ""
method = 'name'
all_data = input('Enter data in the order of name->surname->phone->name.. :')
all_data += " "
for index , item in enumerate(all_data):
    if item == " ":
        if method == 'name' : 
            names.append(temp)
            method = 'surname'
            temp = ""
        elif method == 'surname' :
            surnames.append(temp)
            method = 'phone'
            temp = ""
        elif method == 'phone' :
            phones.append(temp)
            method = 'name'
            temp = ""

    else: temp+=item
if len(names) == len(surnames) == len(phones) : 
    print("All done !")   
if len(names) > len(surnames) : 
    print(f'name - {names[len(names)-1]} didnot inserted') 
if len(names) == len(surnames) and len(surnames) > len(phones) : 
    print(f'name - {names[len(names)-1]} and surname - {surnames[len(surnames)-1]} didnot inserted') 


for index in range(len(phones)):
    cursor.execute(insert_data, (names[index], surnames[index], phones[index])) 

all_table = '''
    SELECT * FROM phonebook2 
    ORDER BY id ASC
'''
cursor.execute(all_table)
data = [row for row in cursor.fetchall()]
dataframe = pd.DataFrame(data, columns=['id', 'name', 'surname', 'phone'])
dataframe = dataframe.set_index('id')
connection.commit()

cursor.close()

connection.close()
dataframe.head(100)
#Arya Stark 657-2343 Tirion Lannister 837-9566 Renli Baratheon 373-9542 Taywin Lannister 342-9432 Daeneris Targarien 234-4621

### OFFSET WITH LIMIT

In [ ]:
import psycopg2 as sql
import pandas as pd

connection = sql.connect(
    host='localhost',

    dbname='suppliers',
    user='postgres',
    password='Bakitzhan566*566',
    port='5432'
)

cursor = connection.cursor()
query_data = '''
    SELECT * FROM phonebook2
    OFFSET %s
    LIMIT %s
'''

offset_size = int(input("Size of the offset :"))
limit_size = int(input("Size of the limit :")) 

cursor.execute(query_data , (offset_size,limit_size)) 

data = [row for row in cursor.fetchall()]
dataframe = pd.DataFrame(data, columns=['id', 'name', 'surname', 'phone'])
dataframe = dataframe.set_index('id')
connection.commit()

cursor.close()

connection.close()
dataframe.head(100)

### Deleting

In [ ]:
import psycopg2 as sql
import pandas as pd

connection = sql.connect(
    host='localhost',
    dbname='suppliers',
    user='postgres',
    password='Bakitzhan566*566',
    port='5432'
)

cursor = connection.cursor()

delete_data = '''
    DELETE FROM phonebook2 WHERE {} = %s;
'''

method = input('Do you want to delete by name or phone? ')
if method == 'name':
    name = input('Enter the name: ')
    cursor.execute(delete_data.format(method), (name,))
if method == 'phone':
    phone = input('Enter the phone: ')
    cursor.execute(delete_data.format(method), (phone,))

connection.commit()

cursor.close()

connection.close()

print('Data deleted successfully.')

connection2 = sql.connect(
    host='localhost',
    dbname='suppliers',
    user='postgres',
    password='Bakitzhan566*566',
    port='5432'
)
cursor2 = connection2.cursor()

all_table = '''
    SELECT * FROM phonebook2
    ORDER BY id ASC
'''
cursor2.execute(all_table)
data = [row for row in cursor2.fetchall()]

dataframe = pd.DataFrame(data, columns=['id', 'name', 'surname', 'phone'])
dataframe = dataframe.set_index('id')

cursor2.close()
connection2.close()
dataframe.head(100)